---
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app-rest

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 500
    type:
      - file

# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#reference-appspec-file-structure-hooks-list
hooks:
  ApplicationStop:
    - location: exec/service_stop.sh
      timeout: 30
      runas: ec2-user
  BeforeInstall:
    - location: exec/service_before_install.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: exec/service_after_install.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: exec/service_start.sh
      timeout: 30
      runas: ec2-user
  ValidateService:
    - location: exec/service_validate.sh
      timeout: 60
      runas: ec2-user
...