---
server:
  port: @project.http.port@
  servlet:
    context-path: @project.http.context.path@
---
spring:
  profiles:
    active: @project.spring.profile@
---
# INFO : File appender disabled due to `app-rest` installation as `init.d` Service (see `deployment-install` under README.md for more)
# BUG  :  Work around of https://github.com/spring-projects/spring-boot/issues/12510
logging.file: app-rest.log
logging:
  file:
    max-history: 5
    max-size: 10MB
---
# https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup
spring:
  flyway:
    locations: classpath:migration/{vendor}
    # Available properties listed in FlywayProperties.java
    installedBy: @project.flayway.installedBy@
    #
    url: @project.database.url@
    user: @project.database.username@
    password: @project.database.password@
---
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  datasource:
    # Use MySQL dialect
    platform: mysql
    #
    url: @project.database.url@
    username: @project.database.username@
    password: @project.database.password@
  jpa:
    hibernate:
      ddl-auto: none
      # Naming strategies for use with Hibernate entities
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)
    properties:
      hibernate:
        # Do not initialize the schema on startup
        hbm2ddl:
          auto: none
        # Show each migration query
        show_sql: true
        # Format each migration query
        format_sql: true
        # The SQL dialect makes Hibernate generate better SQL
        dialect: org.hibernate.dialect.MySQL5Dialect
        dialect.storage_engine: innodb
...