def aws_region = ""
def aws_bucket = ""

def http_host = ""

def database_host = ""
def database_port = ""
def database_name = ""
def database_username = ""
def database_password = ""

pipeline {

    //-----------------------------------------
    // Declarative Pipeline Syntax Reference :: https://jenkins.io/doc/book/pipeline/syntax/#declarative-pipeline
    // Declarative Pipeline Steps Reference  :: https://jenkins.io/doc/pipeline/steps/
    //-----------------------------------------

    // default agent - docker container
    agent {
        docker {
            image "pduleba/blueocean-agent:latest"
            args '-v /D/docker/agent/.m2:$HOME/.m2'
        }
    }

    environment {
        // Access to AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY via "CloudBees AWS Credentials Plugin"
        AWS                 = credentials('aws-credentials')
        AWS_DEFAULT_REGION  = credentials('aws-default-region')
        AWS_DEFAULT_OUTPUT  = credentials('aws-default-output')

        EXEC_ROOT_PATH      = "util-IaaC"
        APP_ROOT_PATH       = "app-rest"
        BUILD_OUTPUT_PATH   = "${env.APP_ROOT_PATH}/target"
        // Depends on pipeline-utility-steps (https://wiki.jenkins.io/display/JENKINS/Pipeline+Utility+Steps+Plugin)
        ARTIFACT_ID         = readMavenPom(file: "${env.APP_ROOT_PATH}/pom.xml").getArtifactId()
        VERSION             = readMavenPom(file: "${env.APP_ROOT_PATH}/pom.xml").getVersion()
    }

    options {
        disableConcurrentBuilds()
    }

    parameters {
        choice choices: ['dev', 'test'], description: 'Target environment', name: 'TARGET_ENVIRONMENT'
        choice choices: ['aws', 'local'], description: 'Maven profile', name: 'MAVEN_PROFILE'
        choice choices: ['true', 'false'], description: 'Release dry run', name: 'DRY_RUN'
    }

    tools {
        "maven" "3.6.1"
    }

    stages {

        stage("SSM parameter store") {
            steps {
                dir("$EXEC_ROOT_PATH") {
                    script {
                        def json = sh(returnStdout : true, script: "exec/ux/utils/get-parameters.sh " +
                                "${params.TARGET_ENVIRONMENT}")

                        aws_region  = "$AWS_DEFAULT_REGION"
                        aws_bucket  = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "http/host <<< ${json}").trim()

                        http_host   = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "http/host <<< ${json}").trim()

                        database_host  = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "database/host <<< ${json}").trim()
                        database_port  = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "database/port <<< ${json}").trim()
                        database_name  = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "database/name <<< ${json}").trim()
                        database_username  = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "database/username <<< ${json}").trim()
                        database_password  = sh(returnStdout : true, script: "exec/ux/utils/find-parameter.sh " +
                                "database/password <<< ${json}").trim()
                    }
                }
            }
        }

        stage("Configuration review") {
            steps {
                sh "echo AWS_ACCESS_KEY_ID      = $AWS_ACCESS_KEY_ID"
                sh "echo AWS_SECRET_ACCESS_KEY  = $AWS_SECRET_ACCESS_KEY"
                sh "echo AWS_DEFAULT_REGION     = $AWS_DEFAULT_REGION"
                sh "echo AWS_DEFAULT_OUTPUT     = $AWS_DEFAULT_OUTPUT"

                sh "echo EXEC_ROOT_PATH         = $EXEC_ROOT_PATH"
                sh "echo APP_ROOT_PATH          = $APP_ROOT_PATH"
                sh "echo BUILD_OUTPUT_PATH      = $BUILD_OUTPUT_PATH"
                sh "echo ARTIFACT_ID            = $ARTIFACT_ID"
                sh "echo VERSION                = $VERSION"

                sh "echo TARGET_ENVIRONMENT     = ${params.TARGET_ENVIRONMENT}"
                sh "echo MAVEN_PROFILE          = ${params.MAVEN_PROFILE}"
                sh "echo DRY_RUN                = ${params.DRY_RUN}"

                sh "echo aws_region             = ${aws_region}"
                sh "echo aws_bucket             = ${aws_bucket}"

                sh "echo http_host              = ${http_host}"

                script {
                    sh "echo database_host          = ${database_host}"
                    sh "echo database_port          = ${database_port}"
                    sh "echo database_name          = ${database_name}"
                    sh "echo database_username      = ${database_username}"
                }

                sh "mvn -B --version"
                sh "echo ${env.MAVEN_HOME}"
                sh "aws --version"
            }
        }

        stage("Maven clean") {
            steps {
                dir("$APP_ROOT_PATH") {
                    sh "mvn -B clean release:clean"
                }
            }
        }


        stage("Maven release") {
            steps {
                dir("$APP_ROOT_PATH") {
                    sh "mvn -B release:prepare release:perform -DdryRun=${params.DRY_RUN} -P${params.MAVEN_PROFILE}"
                }
            }
        }

        stage("Is release valid?") {
            steps {
                script {
                    try {
                        timeout(time: 5, unit: "MINUTES") {
                            input message: 'Is release valid?', ok: 'Yes'
                        }
                        echo "Release has been approved"
                    } catch (err) {
                        echo "Release has not been approved"
                        throw err
                    }
                }
            }
        }

        stage("CodeDeploy") {
            steps {
                dir("$BUILD_OUTPUT_PATH") {
                    sh "ls -alt"
                }
            }
        }
    }

    post {
        cleanup {
            sh "rm -rf $BUILD_OUTPUT_PATH"
        }
    }
}

def valueMasking(String value) {
    return value?.trim() ? "*****" : "";
}